# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
github: https://github.com/mick-whats
logo_title: MyLogo
blog_title: mick-labo

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
  - recent_posts
  - tag
  - archive

# Miscellaneous
wx_block: false
google_analytics:
  enabled: true
  id: UA-129785600-1
favicon:
twitter: https://twitter.com/mick_x_
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:
